{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "teamvault.fullname" . }}-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    # Run before the deployment
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.migration.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "teamvault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "teamvault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: {{ include "teamvault.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/teamvault-server
          args:
            - migrate
            - --database-url=$(TEAMVAULT_DATABASE_URL)
          env:
            - name: TEAMVAULT_DATABASE_URL
              {{- if .Values.database.existingSecret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.urlKey }}
              {{- else if .Values.postgresql.enabled }}
              value: {{ include "teamvault.databaseURL" . | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "teamvault.fullname" . }}-db
                  key: database-url
              {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
