{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamvault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
data:
  {{- if .Values.secrets.masterKey }}
  {{ .Values.secrets.masterKeyKey }}: {{ .Values.secrets.masterKey | b64enc | quote }}
  {{- else }}
  {{ .Values.secrets.masterKeyKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  {{ .Values.secrets.jwtSecretKey }}: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  {{ .Values.secrets.jwtSecretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}

---
{{- if not .Values.database.existingSecret }}
{{- if not .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamvault.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  database-url: {{ include "teamvault.databaseURL" . | b64enc | quote }}
{{- end }}
{{- end }}

---
{{- if .Values.config.oidcClientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamvault.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
type: Opaque
data:
  client-secret: {{ .Values.config.oidcClientSecret | b64enc | quote }}
{{- end }}

---
{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) (not .Values.tls.certManager) }}
{{- if and .Values.tls.cert .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teamvault.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "teamvault.labels" . | nindent 4 }}
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.tls.key | b64enc | quote }}
{{- end }}
{{- end }}
